- name: install pacakges
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: print names
    ansible.builtin.package:
      name: "{{ item.name }}"
      name: "{{ item.state }}"
  loop:
  - { name: "nginx",state: "absent" }
  - { name: "mysql",state: "absent" }
  - { name: "nginx",state: "latest" }